version: '3'
services:
  # Node.js application
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    

  # MySQL
  mysql:
    build: 
      context: .
      dockerfile: database/Dockerfile
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - wp
  

  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./utils/docker-data/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - wp

networks:
  wp:
