services:
  app:
    container_name: wp1c_app
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
      - ${DOCKER_SOCKET_PATH}:${DOCKER_SOCKET_PATH}
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wp

  mysql:
    container_name: wp1c_mysql
    build: 
      context: ./database
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - wp
  
  nginx:
    container_name: wp1c_nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./utils/docker-data/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - wp

networks:
  wp:

volumes:
  mysql_data:
