version: '3'
services:
  app:
    container_name: wp1c_app
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ${DOCKER_SOCKET_PATH}:${DOCKER_SOCKET_PATH}
      - ./:/app
    ports:
      - "3000:3000"
    networks:
      - wp

  mysql:
    container_name: wp1c_mysql
    build: 
      context: ./database
      dockerfile: Dockerfile
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - wp
  
  nginx:
    container_name: wp1c_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./utils/docker-data/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - wp

networks:
  wp:
